id: IE31E41F6
legacy_id: P003178
ocr_import_info:
  bdrc_scan_id: W20907
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T01:57:41'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-01T13:46:09.558447+00:00'
last_modified: 2022-09-01 21:46:14.264286
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W20907
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW20907
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: སྒང་སྟེང་སྤྲུལ་སྐུ་བསྟན་འཛིན་ལེགས་པའི་དོན་གྲུབ་དང་མཚམས་བྲག་བླ་མ་ངག་དབང་འབྲུག་པའི་རྣམ་ཐར།
  author: འབྲུག་རྗེ་མཁན་པོ ༡༠་བསྟན་འཛིན་ཆོས་རྒྱལ།
statistics:
  ocr_word_mean_confidence_index: 0.9655825321029112
  ocr_word_median_confidence_index: 0.9900000095367432
quality: null
bases:
  I00KG03936:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00KG03936
      total_pages: 496
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I00KG03936.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9655825321029112
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
