id: IE31E41F6
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T01:57:45+00:00'
last_modified: '2022-06-07T18:06:54.948813+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W20907
  title: སྒང་སྟེང་སྤྲུལ་སྐུ་བསྟན་འཛིན་ལེགས་པའི་དོན་གྲུབ་དང་མཚམས་བྲག་བླ་མ་ངག་དབང་འབྲུག་པའི་རྣམ་ཐར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '9311':
      image_group_id: I00KG03936
      title: ''
      total_pages: 496
      order: 1
      base_file: 9311.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
