id: P003178
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-17 10:45:27.127100
source_metadata:
  id: bdr:W20907
  title: སྒང་སྟེང་སྤྲུལ་སྐུ་བསྟན་འཛིན་ལེགས་པའི་དོན་གྲུབ་དང་མཚམས་བྲག་བླ་མ་ངག་དབང་འབྲུག་པའི་རྣམ་ཐར།
  author: ''
  volumes:
    e233a98eda264beb963e2f081e87cda7:
      image_group_id: I00KG03936
      title: ''
      volume_number: 1
      total_pages: 496
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
