id: opecha:P003178
initial_creation_type: ocr
source_metadata:
  id: bdr:W20907
  title: སྒང་སྟེང་སྤྲུལ་སྐུ་བསྟན་འཛིན་ལེགས་པའི་དོན་གྲུབ་དང་མཚམས་བྲག་བླ་མ་ངག་དབང་འབྲུག་པའི་རྣམ་ཐར།
  volume: ''
  author: ''
