id: P003178
initial_creation_type: ocr
source_metadata:
  id: bdr:W20907
  title: སྒང་སྟེང་སྤྲུལ་སྐུ་བསྟན་འཛིན་ལེགས་པའི་དོན་གྲུབ་དང་མཚམས་བྲག་བླ་མ་ངག་དབང་འབྲུག་པའི་རྣམ་ཐར།
  author: ''
  volumes:
    e233a98eda264beb963e2f081e87cda7:
      image_group_id: I00KG03936
      title: ''
      volume_number: 1
      total_pages: 496
